// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWqh9Kk3v_EBFKg9let7t1SLpPsYXAizQ',
    appId: '1:489553611912:web:2743fa31fafe9e7201233d',
    messagingSenderId: '489553611912',
    projectId: 'ditonton-5a135',
    authDomain: 'ditonton-5a135.firebaseapp.com',
    storageBucket: 'ditonton-5a135.appspot.com',
    measurementId: 'G-TYQLMVDT6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOafBIUjFSJIMCjEU6pLK3mvud8s55TP4',
    appId: '1:489553611912:android:b10dc45762fd45be01233d',
    messagingSenderId: '489553611912',
    projectId: 'ditonton-5a135',
    storageBucket: 'ditonton-5a135.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvLUfCHANBh35NugjmGvFKi6LUeDZJuyA',
    appId: '1:489553611912:ios:47600423617d59d201233d',
    messagingSenderId: '489553611912',
    projectId: 'ditonton-5a135',
    storageBucket: 'ditonton-5a135.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
